import type { CanvasNode, EdgeConfig } from './types';

export const DEFAULT_SYSTEM_NODES: CanvasNode[] = [
  {
    id: 'node-0',
    type: 'producer',
    label: 'Event Producer',
    throughputPerSec: 10,
    latencyMs: 5,
    x: 80,
    y: 220,
  },
  {
    id: 'node-1',
    type: 'api_gateway',
    label: 'API Gateway',
    throughputPerSec: 11,
    latencyMs: 15,
    timeoutMs: 250,
    x: 260,
    y: 220,
  },
  {
    id: 'node-2',
    type: 'producer',
    label: 'Priority Producer',
    throughputPerSec: 2,
    latencyMs: 5,
    x: 80,
    y: 320,
  },
  {
    id: 'node-3',
    type: 'kafka',
    label: 'Kafka Cluster',
    partitions: 6,
    throughputPerSec: 300,
    latencyMs: 5,
    x: 440,
    y: 220,
  },
  {
    id: 'node-4',
    type: 'consumer_group',
    label: 'Consumer Group',
    replicas: 4,
    throughputPerSec: 240,
    latencyMs: 12,
    x: 620,
    y: 220,
  },
  {
    id: 'node-5',
    type: 'load_balancer',
    label: 'Load Balancer',
    replicas: 2,
    latencyMs: 4,
    x: 800,
    y: 220,
  },
  {
    id: 'node-6',
    type: 'worker',
    label: 'Worker Pool A',
    replicas: 6,
    throughputPerSec: 180,
    latencyMs: 30,
    failureRate: 0.04,
    x: 960,
    y: 220,
  },
  {
    id: 'node-7',
    type: 'worker',
    label: 'Worker Pool B',
    replicas: 4,
    throughputPerSec: 140,
    latencyMs: 35,
    failureRate: 0.06,
    x: 960,
    y: 360,
  },
  {
    id: 'node-8',
    type: 'cache',
    label: 'Redis Cache',
    cacheHitRate: 0.4,
    throughputPerSec: 500,
    latencyMs: 2,
    x: 1160,
    y: 260,
  },
  {
    id: 'node-9',
    type: 'circuit_breaker',
    label: 'Circuit Breaker',
    circuitBreakerThreshold: 0.35,
    timeoutMs: 2500,
    failureRate: 0.06,
    x: 1120,
    y: 420,
  },
  {
    id: 'node-10',
    type: 'database',
    label: 'PostgreSQL',
    sink: true,
    throughputPerSec: 120,
    latencyMs: 20,
    failureRate: 0.02,
    x: 1320,
    y: 260,
  },
  {
    id: 'node-11',
    type: 'dead_letter_queue',
    label: 'DLQ',
    throughputPerSec: 100,
    x: 1320,
    y: 460,
  },
];

export const DEFAULT_SYSTEM_EDGES: EdgeConfig[] = [
  { id: 'edge-0', sourceId: 'node-0', targetId: 'node-1' },
  { id: 'edge-1', sourceId: 'node-2', targetId: 'node-1' },
  { id: 'edge-2', sourceId: 'node-1', targetId: 'node-3' },
  { id: 'edge-3', sourceId: 'node-3', targetId: 'node-4' },
  { id: 'edge-4', sourceId: 'node-4', targetId: 'node-5' },
  { id: 'edge-5', sourceId: 'node-5', targetId: 'node-6' },
  { id: 'edge-6', sourceId: 'node-5', targetId: 'node-7' },
  { id: 'edge-7', sourceId: 'node-6', targetId: 'node-8' },
  { id: 'edge-8', sourceId: 'node-7', targetId: 'node-8' },
  { id: 'edge-9', sourceId: 'node-8', targetId: 'node-9' },
  { id: 'edge-10', sourceId: 'node-9', targetId: 'node-10' },
  { id: 'edge-11', sourceId: 'node-9', targetId: 'node-11' },
];
