import type { CanvasNode, EdgeConfig } from './types';

export const DEFAULT_SYSTEM_NODES: CanvasNode[] = [
  {
    id: 'node-0',
    type: 'producer',
    label: 'Event Producer',
    throughputPerSec: 1000,
    latencyMs: 10,
    x: 120,
    y: 220,
  },
  {
    id: 'node-1',
    type: 'kafka',
    label: 'Kafka Cluster',
    partitions: 3,
    throughputPerSec: 5000,
    latencyMs: 5,
    x: 320,
    y: 220,
  },
  {
    id: 'node-2',
    type: 'consumer_group',
    label: 'Consumer Group',
    replicas: 3,
    throughputPerSec: 800,
    latencyMs: 20,
    x: 520,
    y: 220,
  },
  {
    id: 'node-3',
    type: 'load_balancer',
    label: 'Load Balancer',
    replicas: 2,
    throughputPerSec: 2000,
    latencyMs: 5,
    x: 720,
    y: 220,
  },
  {
    id: 'node-4',
    type: 'worker',
    label: 'Worker Pool',
    replicas: 5,
    throughputPerSec: 500,
    latencyMs: 50,
    failureRate: 0.05,
    x: 920,
    y: 220,
  },
  {
    id: 'node-5',
    type: 'cache',
    label: 'Redis Cache',
    cacheHitRate: 0.8,
    throughputPerSec: 10000,
    latencyMs: 2,
    x: 920,
    y: 80,
  },
  {
    id: 'node-6',
    type: 'database',
    label: 'PostgreSQL',
    throughputPerSec: 1000,
    latencyMs: 15,
    failureRate: 0.01,
    x: 1120,
    y: 220,
  },
  {
    id: 'node-7',
    type: 'circuit_breaker',
    label: 'Circuit Breaker',
    circuitBreakerThreshold: 0.5,
    timeoutMs: 3000,
    failureRate: 0.1,
    x: 1120,
    y: 360,
  },
  {
    id: 'node-8',
    type: 'dead_letter_queue',
    label: 'DLQ',
    throughputPerSec: 100,
    x: 1320,
    y: 360,
  },
];

export const DEFAULT_SYSTEM_EDGES: EdgeConfig[] = [
  { id: 'edge-0', sourceId: 'node-0', targetId: 'node-1' },
  { id: 'edge-1', sourceId: 'node-1', targetId: 'node-2' },
  { id: 'edge-2', sourceId: 'node-2', targetId: 'node-3' },
  { id: 'edge-3', sourceId: 'node-3', targetId: 'node-4' },
  { id: 'edge-4', sourceId: 'node-4', targetId: 'node-5' },
  { id: 'edge-5', sourceId: 'node-5', targetId: 'node-6' },
  { id: 'edge-6', sourceId: 'node-4', targetId: 'node-7' },
  { id: 'edge-7', sourceId: 'node-7', targetId: 'node-8' },
];
